name: Publish to PyPI

on:
  push:
    branches:
      - main
  # Also allow manual triggering from the GitHub UI
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and upload to PyPI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build Source and Wheel Distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # This requires you to add your PyPI token to GitHub Repository Secrets
          password: ${{ secrets.PYPI_API_TOKEN }}
